### ISSUE TITLE
peer feedback

### ISSUE THREAD

**Issue by doraqmon** [UBC-MDS/DSCI_522_Group_409#53]
1. For the model, maybe look at the R2 as well.
2. the first EDA can be reduced to one as all the plots are very similar. Maybe classify as weekend vs. weekday

**Comment by doraqmon** [comment]
1. check the r2 after selecting model
2. change the first plot in EDA part to weekday vs cnt

**Comment by doraqmon** [comment]
1 - Aman
2 - Victor

**Comment by amank90** [comment]
Will start working on r2 part on modeling script and also put better test function for data  download and data modeling

**Comment by vcuspinera** [comment]
I leave the first plot as it is but also add other plot with using workdays. You can find them [here](https://github.com/UBC-MDS/DSCI_522_Group_409/tree/master/img).

**Comment by doraqmon** [comment]
great! I will modify the changes into report

**Comment by doraqmon** [comment]
I have added the updated correlation matrix to the report

**Comment by amank90** [comment]
done with r2 score

**Comment by doraqmon** [comment]
all the issues have been addressed!
