### ISSUE TITLE
Peer Review - Karan/Sakariya

### ISSUE THREAD

**Issue by amank90** [UBC-MDS/DSCI_522_Group_409#54]
- The seasonality effect of rental bikes can be explored more.
- Computational time can be included in the model output as done by Karan's Team
- Research question on readme.md

**Comment by doraqmon** [comment]
1. Optional, will do the box plot of weather vs cnt in EDA 
2. include the time in the modeling script
3. I will update the readme with research question

**Comment by doraqmon** [comment]
1 - optional, Victor
2 - Aman
3 - Dora

**Comment by amank90** [comment]
Will work on computational time part

**Comment by vcuspinera** [comment]
Plots done, you can find them [here](https://github.com/UBC-MDS/DSCI_522_Group_409/tree/master/img).

**Comment by doraqmon** [comment]
point 3 is done

**Comment by amank90** [comment]
computational time added

**Comment by doraqmon** [comment]
All the issues have been fixed! point 1 is optional
