### ISSUE TITLE
Lab feedback - Holly and Cari

### ISSUE THREAD

**Issue by vcuspinera** [UBC-MDS/DSCI_522_Group_409#55]
- "Label encoding" could be use for the "weathersit".
- Explain in the final report also at the beginning the variables to be understandable, or link to another report.
- Maybe remove features that doesn't help much to the model and see how the results change

**Comment by doraqmon** [comment]
1. It's already used in the dataset. maybe try one-hot encoding.
2. Update the report with the list of features as in proposal.
3. try feature selection , e.g. forward selection

**Comment by doraqmon** [comment]
1. optional
2. Dora
3 - Aman, optional

**Comment by doraqmon** [comment]
I have added the description of fetaures into report

**Comment by doraqmon** [comment]
point 1- It is already label encoding and we do not think one-hot-encoding will improve the model. 
all the other issues have been fixed!
