### ISSUE TITLE
some minor issues from TA 

### ISSUE THREAD

**Issue by doraqmon** [UBC-MDS/DSCI_522_Group_409#63]
Hi,
as discussed with TA on slack, we need to address the following 2 minor issues.
1. make the last plot on EDA report looks nicer
2. write docstring for functions.

**Comment by vcuspinera** [comment]
Sounds good, I will do the point 1, and also ad dock string to the function in the EDA script

**Comment by vcuspinera** [comment]
I made the dock string at EDA script and [the plot](https://github.com/UBC-MDS/DSCI_522_Group_409/tree/master/img).

**Comment by doraqmon** [comment]
I have put docstring under all the scripts! Complete 2

**Comment by doraqmon** [comment]
Complete fixing these 2 issues!
