### ISSUE TITLE
Visualizations Feedback!

### ISSUE THREAD

**Issue by firasm** [UBC-MDS/DSCI_522_Group_409#71]
- Below are some thoughts about the visualizations in this report and some suggestions for improvement, and notes when things are done well. You should implement these in milestone4
- - [x] It would really have helped if you had a caption and a figure/table number for each plot. That way you can easily reference it in your text, and it's easier for readers to find
- - [x] Figure 1: working day/temperature
	- - [x] This is a really powerful visualization. I think there is some overplotting happening, but it's not actually interfering with your overall message and what you're trying to convey
	- - [x] I would suggest you add better facet titles/subtitles. So rather than workingday no/yes, maybe remove the 'workingday' title and instead of no/yes, change to Not a working day/Working day in larger text size. Let me know if you need help doing this in altair!
- - [x] Figure 2:
	- - [x] Also a really powerful visualization that shows exactly what you want it to!
	- - [x] If you add a figure number and caption, this will be even more effective
	- - [x] Consider setting the lower limit of your colour bar to 0 rather than 4
- - [x] Figure 3:
	- - [x] Great work! This is really excellent. I've submitted this one to the altair examples dir as Victor sent me a minimum working example
	- - [ ] Ideally, you only want to show half the correlation map as the other half is redundant (see example [here](http://www.sthda.com/sthda/RDoc/figure/ggplot2/ggplot2-correlation-matrix-heatmap-add-correlation-coefficients-1.png)) - let me know if you figure out how to do this in Altair
- - [x] Table 1:
	- - [x] Too many sig figs, there's no need to show that many, it hurts readability and interpretability
- - [x] Figure: importance of predictors and actual vs. predicted rides
	- - [x] perfect! Well done here
- - [x] Overall the report looks very polished and clean! Great work! Excellent work with your labels, titles, and plot choices! For every plot I was immediately able to understand what you were trying to convey.

**Comment by doraqmon** [comment]
Figure 3: we did not find the solution to show half of the correlation maps. We will mark it optional.

**Comment by doraqmon** [comment]
For the figure number and captions, we tried several times with the same code, it showed up in 2/5 times due to some unknown reason.

**Comment by firasm** [comment]
RE: Figure 3, for future reference, here is some sample code to do this:

```
# Load packages
import altair as alt
from vega_datasets import data

# Load the data
df_iris = data.iris()

# This bit of wrangling creates a new dataframe with only half the elements
l1 = sorted(df_iris.corr().columns.to_list())
l2 = l1.copy()
rows = []

for e1 in l1:
    for e2 in l2:
        rows.append([e1,e2, df_iris.corr().loc[e1,e2]])
        
    l2.remove(e1)
    
# Create dataframe from list of rows
newdf = pd.DataFrame(rows,columns=['Var1','Var2','Corr'])

# If you want to remove the diagonals
newdf = newdf[newdf['Var1']!=newdf['Var2']]

# Create the heatmap first
heatmap = alt.Chart(newdf).mark_rect(
).encode(
    alt.X('Var1:O', title = ''),
    alt.Y('Var2:O', title = '', axis=alt.Axis(labelAngle=0)),
     alt.Color('Corr:Q',
                scale=alt.Scale(scheme='viridis'))
)

# Add the correlation values as a text mark
text = heatmap.mark_text(baseline='middle', fontSize=20).encode(
    text=alt.Text('Corr:Q', format='.2'),
    color=alt.condition(
        alt.datum['Corr'] >= 0.95,
        alt.value('black'),
        alt.value('white')
    )
)

# Set the height, width, title and other properties
corrMatrix_chart = (heatmap + text).properties(
    width = 400,
    height = 400,
    title = "Iris variables correlation matrix",
)
corrMatrix_chart.configure_axis(
    labelFontSize=18,
    titleFontSize=24,
).configure_title(
    fontSize=24,
    anchor='start',
).configure_legend(
    labelFontSize=20,
    titleFontSize=20)
```
![visualization-17](https://user-images.githubusercontent.com/2507459/74091059-1524aa00-4a68-11ea-8348-ef0913d7961e.png)
