### ISSUE TITLE
Dockerfile on Docker Hub

### ISSUE THREAD

**Issue by vcuspinera** [UBC-MDS/DSCI_522_Group_409#80]
Hi guys, I create the dockerfile that Aman made, in my docker hub successfully; you will find it as: **vcuspinera/dsci_522_group_409**

To run it, in your computer in the terminal you should go to your repository where you have the *DSCI_522_Group_409* project and run the next command:  
```
docker run --rm -v /$(pwd):/home/analysis vcuspinera/dsci_522_group_409:v1.0 make -C '/home/analysis' all
```

**Comment by doraqmon** [comment]
thank you Victor!
